Script started on 2019-09-11 17:02:39-07:00 [TERM="xterm-256color" TTY="/dev/pts/2" COLUMNS="123" LINES="24"]
sehoon@sehoon-VirtualBox: ~/c9.io/cs012_assignment/home/workspace/cs100/RSHELL./rshell$ make
rm -rf bin
mkdir bin
g++ -Wall -Werror -ansi -pedantic src/rshell.cpp -o bin/rshell
sehoon@sehoon-VirtualBox: ~/c9.io/cs012_assignment/home/workspace/cs100/RSHELL./rshell$ ./bin/rshell
$ (echo 1) && (echo 2) || (echo 3)
1
2
$ (echo 1) && (echo 2) || (echo 3) && (echo 4)
1
2
4
$ (echo 1) && (echo 2) || (echo 3) || (echo 4)
1
2
$ (echo 0 || (echo 1 && (echo 2) || (echo 3) && echo 4))
0
$ (echo 0 || (echo 1 && (echo 2) || (echo 3) && echo 4) && echo 5)
0
5
$ exit
sehoon@sehoon-VirtualBox: ~/c9.io/cs012_assignment/home/workspace/cs100/RSHELL./rshell$ exit
exit

Script done on 2019-09-11 17:03:18-07:00 [COMMAND_EXIT_CODE="1"]
